### ISSUE TITLE
ERROR : 'get' command failed. Version is 1.39.11

### ISSUE THREAD

**Issue by bsimmons123** [itzg/docker-mc-proxy#219]
```
velocity-proxy  | [mc-image-helper] 21:05:09.856 ERROR : 'get' command failed. Version is 1.39.11
velocity-proxy  | me.itzg.helpers.get.RequestFailedException: Failed to download https://papermc.io/api/v2/projects/velocity: status code: 403, reason phrase: Forbidden
velocity-proxy  |       at me.itzg.helpers.get.GetCommand.processSingleUri(GetCommand.java:442)
velocity-proxy  |       at me.itzg.helpers.get.GetCommand.call(GetCommand.java:188)
velocity-proxy  |       at me.itzg.helpers.get.GetCommand.call(GetCommand.java:55)
velocity-proxy  |       at picocli.CommandLine.executeUserObject(CommandLine.java:2045)
velocity-proxy  |       at picocli.CommandLine.access$1500(CommandLine.java:148)
velocity-proxy  |       at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
velocity-proxy  |       at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
velocity-proxy  |       at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
velocity-proxy  |       at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
velocity-proxy  |       at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
velocity-proxy  |       at picocli.CommandLine.execute(CommandLine.java:2174)
velocity-proxy  |       at me.itzg.helpers.McImageHelper.main(McImageHelper.java:159)
velocity-proxy  | Caused by: org.apache.hc.client5.http.HttpResponseException: status code: 403, reason phrase: Forbidden
velocity-proxy  |       at org.apache.hc.client5.http.impl.classic.AbstractHttpClientResponseHandler.handleResponse(AbstractHttpClientResponseHandler.java:68)
velocity-proxy  |       at me.itzg.helpers.http.LoggingResponseHandler.handleResponse(LoggingResponseHandler.java:20)
velocity-proxy  |       at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:247)
velocity-proxy  |       at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:188)
velocity-proxy  |       at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:162)
velocity-proxy  |       at me.itzg.helpers.get.GetCommand.processSingleUri(GetCommand.java:440)
velocity-proxy  |       ... 11 common frames omitted
velocity-proxy  | ERROR: failed to lookup PaperMC versions
```

Looks like a similar issue to [#2207](https://github.com/itzg/docker-minecraft-server/issues/2207)

**Comment by ImStveL** [comment]
PaperMC seems to have stopped using that endpoint. Visiting the download link shows so. https://papermc.io/api/v2/projects/velocity.

The current download link on the PaperMC website seems to be now https://api.papermc.io/v2/projects/velocity/

**Comment by aaronjamt** [comment]
> PaperMC seems to have stopped using that endpoint. Visiting the download link shows so. https://papermc.io/api/v2/projects/velocity.
> 
> The current download link on the PaperMC website seems to be now https://api.papermc.io/v2/projects/velocity/
> 
> EDIT: A workaround that's working on my end is to set the environment variables 'TYPE' to custom and 'BUNGEE_JAR_URL' to the new PaperMC link

Can confirm this works for me. I've specifically put the link to the latest version of the Velocity server as the URL. For anyone else who needs it, here are the variables that work around this issue until #220 is merged:
```
TYPE: "CUSTOM"
BUNGEE_JAR_URL: "https://api.papermc.io/v2/projects/velocity/versions/3.4.0-SNAPSHOT/builds/458/downloads/velocity-3.4.0-SNAPSHOT-458.jar"
```
